language: php

# php compatibility
php:
  - 7.0
#  - 7.1
#  - 7.2

services:
  - mysql
  - docker

env:
    - COVERAGE_PHP_VERSION: 7.2

# Needed for docker support
sudo: required

before_script:
  # msodbcsql17
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - curl https://packages.microsoft.com/config/ubuntu/14.04/prod.list | sudo tee -a /etc/apt/sources.list.d/msodbcsql17.list
  - sudo apt-get update --quiet --quiet
  - apt-cache policy msodbcsql17 unixodbc unixodbc-dev libssl1.0.0
  - sudo ACCEPT_EULA=Y apt-get install --quiet --yes msodbcsql17 unixodbc unixodbc-dev libssl1.0.0
  # ms sql server php driver
  - pecl channel-update pecl.php.net
  - pecl search sqlsrv
  - pecl install sqlsrv pdo_sqlsrv
  - echo -e "\n; Microsoft Drivers for PHP for SQL Server\n\nextension=sqlsrv.so\nextension=pdo_sqlsrv.so" > ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # ms sql server
  - docker pull microsoft/mssql-server-linux
  - docker run --name dbal-mssql -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password-123456' -p 1433:1433 -d microsoft/mssql-server-linux
  - docker ps -a
  # test connections
  - docker exec dbal-mssql /opt/mssql-tools/bin/sqlcmd -U sa -P 'Password-123456' -Q "SELECT @@VERSION"
  - php tests/sqlsrv-direct-connection.php localhost sa 'Password-123456'
  # project
  - phpenv config-rm xdebug.ini
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - cp tests/.env.travis tests/.env
  - mkdir -p build/tests/
  - vendor/bin/phplint
  - vendor/bin/phpcs -sp src/ tests/
  - vendor/bin/php-cs-fixer fix --using-cache=no --dry-run --verbose
  - |
    if [[ $TRAVIS_PHP_VERSION == $COVERAGE_PHP_VERSION ]]; then
        php -dzend_extension=xdebug.so vendor/bin/phpunit --coverage-text --coverage-clover=build/tests/coverage.xml
    else
        php vendor/bin/phpunit
    fi

after_script:
  # upload to scrutinizer
  - |
    if [[ $TRAVIS_PHP_VERSION == $COVERAGE_PHP_VERSION ]]; then
        wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover build/tests/coverage.xml
    fi

notifications:
  email: false
